services:
  - type: web
    name: quantum-internet
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: sambanova-keys
